package de.seuhd.campuscoffee.api.mapper

import de.seuhd.campuscoffee.api.dtos.ReviewDto
import de.seuhd.campuscoffee.domain.model.objects.Review
import de.seuhd.campuscoffee.domain.ports.api.PosService
import de.seuhd.campuscoffee.domain.ports.api.UserService
import org.mapstruct.Mapper
import org.mapstruct.Mapping
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean

/**
 * Mapper between the [Review] domain model and [ReviewDto]. `fromDomain` is generated by MapStruct from
 * the `@Mapping`s below; `toDomain` is hand-written because it resolves the referenced POS and author
 * through the services and resets the approval state.
 */
@Mapper(componentModel = "spring")
@ConditionalOnMissingBean // prevent IntelliJ warning about duplicate beans
abstract class ReviewDtoMapper : DtoMapper<Review, ReviewDto> {

    // internal, not protected: MapStruct's generated subclass and the same-module test both inject these,
    // and a protected member is not visible to a test in the same package
    @Autowired
    internal lateinit var posService: PosService

    @Autowired
    internal lateinit var userService: UserService

    @Mapping(target = "posId", source = "pos.id")
    @Mapping(target = "authorId", source = "author.id")
    abstract override fun fromDomain(source: Review): ReviewDto

    /**
     * Builds a domain review from the DTO, resolving the referenced POS and author by id. A new review
     * always starts unapproved with a zero approval count; the DTO's `approved` value is ignored.
     */
    override fun toDomain(source: ReviewDto): Review = Review(
        id = source.id,
        createdAt = source.createdAt,
        updatedAt = source.updatedAt,
        pos = posService.getById(source.posId!!),
        author = userService.getById(source.authorId!!),
        review = source.review!!,
        approved = false,
        approvalCount = 0,
    )
}
